apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {appName}-build
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {gitRepoUrl}
    targetRevision: HEAD
    path: .helm/build
    helm:
      valueFiles:
        - values-build.yaml
  destination:
    server: {clusterApiUrl}
    namespace: {namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
